### Upload file to bucket
POST localhost:8080/api/files/1
Authorization: Bearer {{token}}
Content-Type: multipart/form-data; boundary=boundary

--boundary
Content-Disposition: form-data; name="file"; filename="testfile.txt"

// File content
< ./resources/testfile.txt

### Download file from bucket and directory
GET localhost:8080/api/files/1/p1%2Fsub1%2Fu1%2F42%2F807%2Fmartin.txt
Authorization: Bearer {{token}}